// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoEvaluation.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoEvaluation.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408233250_CleanRefactorToEntrepriseParSA")]
    partial class CleanRefactorToEntrepriseParSA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeoEvaluation.API.Models.Campagne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCandidats")
                        .HasColumnType("integer");

                    b.Property<int>("NbTentativesMax")
                        .HasColumnType("integer");

                    b.Property<string>("NiveauDifficulte")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonnelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionnaireId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScorePassage")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("Campagnes");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampagneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PostuleLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.HasIndex("CandidatId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.DocumentCandidat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstVerifie")
                        .HasColumnType("boolean");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.ToTable("DocumentCandidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Entreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("MatriculeFiscale")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.EntrepriseParSA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("CodePostal")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Domaine")
                        .HasColumnType("text");

                    b.Property<string>("EmailResponsable")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Industrie")
                        .HasColumnType("text");

                    b.Property<string>("NomResponsable")
                        .HasColumnType("text");

                    b.Property<string>("Pays")
                        .HasColumnType("text");

                    b.Property<string>("PrenomResponsable")
                        .HasColumnType("text");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneResponsable")
                        .HasColumnType("text");

                    b.Property<string>("Ville")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId")
                        .IsUnique();

                    b.ToTable("EntrepriseParSA");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid");

                    b.Property<int>("LimiteTemps")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.InscriptionsEntreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatriculeFiscale")
                        .HasColumnType("text");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrenomResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("TelephoneResponsable")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InscriptionsEntreprises");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Planning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampagneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ModeNotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BonneReponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Poids")
                        .HasColumnType("double precision");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Reponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<double>("ScoreIA")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("SoumiseLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomFamille")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.TokensActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("IdInscription")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Utilise")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TokensActivation");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Privileges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("UserType").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidat", b =>
                {
                    b.HasBaseType("NeoEvaluation.API.Models.Utilisateur");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProfilComplet")
                        .HasColumnType("boolean");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("EntrepriseId");

                    b.HasDiscriminator().HasValue("Candidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Personnel", b =>
                {
                    b.HasBaseType("NeoEvaluation.API.Models.Utilisateur");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdEmploye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("EntrepriseId");

                    b.HasDiscriminator().HasValue("Personnel");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.SuperAdmin", b =>
                {
                    b.HasBaseType("NeoEvaluation.API.Models.Utilisateur");

                    b.HasIndex("EntrepriseId");

                    b.HasDiscriminator().HasValue("SuperAdmin");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Campagne", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", null)
                        .WithMany("Campagnes")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Personnel", null)
                        .WithMany("CampagnesGerees")
                        .HasForeignKey("PersonnelId");

                    b.HasOne("NeoEvaluation.API.Models.Questionnaire", "Questionnaire")
                        .WithMany()
                        .HasForeignKey("QuestionnaireId");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidature", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Campagne", "Campagne")
                        .WithMany("Candidatures")
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagne");

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.DocumentCandidat", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Candidat", "Candidat")
                        .WithMany("Documents")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.EntrepriseParSA", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithOne("DetailsSA")
                        .HasForeignKey("NeoEvaluation.API.Models.EntrepriseParSA", "EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Evaluation", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Candidature", "Candidature")
                        .WithOne("Evaluation")
                        .HasForeignKey("NeoEvaluation.API.Models.Evaluation", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Planning", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Campagne", "Campagne")
                        .WithMany()
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagne");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Question", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Questionnaire", "Questionnaire")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Reponse", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Evaluation", "Evaluation")
                        .WithMany("Reponses")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Utilisateur", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidat", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Personnel", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithMany("Staff")
                        .HasForeignKey("EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.SuperAdmin", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Campagne", b =>
                {
                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidature", b =>
                {
                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Entreprise", b =>
                {
                    b.Navigation("Campagnes");

                    b.Navigation("DetailsSA");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Evaluation", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Questionnaire", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidat", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Personnel", b =>
                {
                    b.Navigation("CampagnesGerees");
                });
#pragma warning restore 612, 618
        }
    }
}
