// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeoEvaluation.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeoEvaluation.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415124957_AddQuestionTimer")]
    partial class AddQuestionTimer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeoEvaluation.API.Models.Campagne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonnelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlanificateurId")
                        .HasColumnType("uuid");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("PlanificateurId");

                    b.ToTable("Campagnes");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.CampagneQuestionnaire", b =>
                {
                    b.Property<Guid>("CampagneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid");

                    b.HasKey("CampagneId", "QuestionnaireId");

                    b.HasIndex("QuestionnaireId");

                    b.ToTable("CampagneQuestionnaires");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampagneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PostuleLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.HasIndex("CandidatId");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.DocumentCandidat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstVerifie")
                        .HasColumnType("boolean");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.ToTable("DocumentCandidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Entreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AbonnementFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CouleurSignature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Langue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MatriculeFiscale")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secteur")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Entreprises");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.EntrepriseParSA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("CodePostal")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Domaine")
                        .HasColumnType("text");

                    b.Property<string>("EmailResponsable")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Industrie")
                        .HasColumnType("text");

                    b.Property<string>("NomResponsable")
                        .HasColumnType("text");

                    b.Property<string>("Pays")
                        .HasColumnType("text");

                    b.Property<string>("PrenomResponsable")
                        .HasColumnType("text");

                    b.Property<string>("SiteWeb")
                        .HasColumnType("text");

                    b.Property<string>("TelephoneResponsable")
                        .HasColumnType("text");

                    b.Property<string>("Ville")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntrepriseId")
                        .IsUnique();

                    b.ToTable("EntrepriseParSA");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CandidatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NbReprises")
                        .HasColumnType("integer");

                    b.Property<float>("ScorePourcentage")
                        .HasColumnType("real");

                    b.Property<float>("ScoreTotal")
                        .HasColumnType("real");

                    b.Property<string>("ScoresParTheme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("CandidatureId")
                        .IsUnique();

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.InscriptionsEntreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatriculeFiscale")
                        .HasColumnType("text");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrenomResponsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("TelephoneResponsable")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InscriptionsEntreprises");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Planning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampagneId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ModeNotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampagneId");

                    b.ToTable("Plannings");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BonneReponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Choix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DureeSecondes")
                        .HasColumnType("integer");

                    b.Property<string>("Enonce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Niveau")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("Prerequis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SousTheme")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Questionnaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AntitricheActif")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CreateurId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DebutDispo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DureeMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstPublie")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FinDispo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxReprises")
                        .HasColumnType("integer");

                    b.Property<bool>("RandomiserQuestions")
                        .HasColumnType("boolean");

                    b.Property<bool>("ReprisesAutorisees")
                        .HasColumnType("boolean");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.ToTable("Questionnaires");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.QuestionnaireQuestion", b =>
                {
                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstObligatoire")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<float>("Ponderation")
                        .HasColumnType("real");

                    b.HasKey("QuestionnaireId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionnaireQuestions");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Rapport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheminPDF")
                        .HasColumnType("text");

                    b.Property<bool>("EstEnvoye")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GenereLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecommandationsIA")
                        .HasColumnType("text");

                    b.Property<string>("ScoresParNiveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoresParTheme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TauxReussite")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId")
                        .IsUnique();

                    b.ToTable("Rapports");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Reponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointsObtenus")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SoumisLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TempsSecondes")
                        .HasColumnType("integer");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomFamille")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.TokensActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("IdInscription")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Utilise")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TokensActivation");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntrepriseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Privileges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleNom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("UserType").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidat", b =>
                {
                    b.HasBaseType("NeoEvaluation.API.Models.Utilisateur");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProfilComplet")
                        .HasColumnType("boolean");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("EntrepriseId");

                    b.HasDiscriminator().HasValue("Candidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Personnel", b =>
                {
                    b.HasBaseType("NeoEvaluation.API.Models.Utilisateur");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdEmploye")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("EntrepriseId");

                    b.HasDiscriminator().HasValue("Personnel");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.SuperAdmin", b =>
                {
                    b.HasBaseType("NeoEvaluation.API.Models.Utilisateur");

                    b.HasIndex("EntrepriseId");

                    b.HasDiscriminator().HasValue("SuperAdmin");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Campagne", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithMany("Campagnes")
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Personnel", null)
                        .WithMany("CampagnesGerees")
                        .HasForeignKey("PersonnelId");

                    b.HasOne("NeoEvaluation.API.Models.Utilisateur", "Planificateur")
                        .WithMany()
                        .HasForeignKey("PlanificateurId");

                    b.Navigation("Entreprise");

                    b.Navigation("Planificateur");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.CampagneQuestionnaire", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Campagne", "Campagne")
                        .WithMany("CampagneQuestionnaires")
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Questionnaire", "Questionnaire")
                        .WithMany("CampagneQuestionnaires")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagne");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidature", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Campagne", "Campagne")
                        .WithMany("Candidatures")
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Candidat", "Candidat")
                        .WithMany("Candidatures")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagne");

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.DocumentCandidat", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Candidat", "Candidat")
                        .WithMany("Documents")
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.EntrepriseParSA", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithOne("DetailsSA")
                        .HasForeignKey("NeoEvaluation.API.Models.EntrepriseParSA", "EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Evaluation", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Utilisateur", "Candidat")
                        .WithMany()
                        .HasForeignKey("CandidatId");

                    b.HasOne("NeoEvaluation.API.Models.Candidature", "Candidature")
                        .WithOne("Evaluation")
                        .HasForeignKey("NeoEvaluation.API.Models.Evaluation", "CandidatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Candidature");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Planning", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Campagne", "Campagne")
                        .WithMany()
                        .HasForeignKey("CampagneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campagne");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Question", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId");

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Questionnaire", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId");

                    b.Navigation("Createur");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.QuestionnaireQuestion", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Question", "Question")
                        .WithMany("QuestionnaireQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Questionnaire", "Questionnaire")
                        .WithMany("QuestionnaireQuestions")
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Questionnaire");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Rapport", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Evaluation", "Evaluation")
                        .WithOne("Rapport")
                        .HasForeignKey("NeoEvaluation.API.Models.Rapport", "EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Reponse", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Evaluation", "Evaluation")
                        .WithMany("Reponses")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeoEvaluation.API.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Utilisateur", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidat", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Personnel", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithMany("Staff")
                        .HasForeignKey("EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.SuperAdmin", b =>
                {
                    b.HasOne("NeoEvaluation.API.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId");

                    b.Navigation("Entreprise");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Campagne", b =>
                {
                    b.Navigation("CampagneQuestionnaires");

                    b.Navigation("Candidatures");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidature", b =>
                {
                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Entreprise", b =>
                {
                    b.Navigation("Campagnes");

                    b.Navigation("DetailsSA");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Evaluation", b =>
                {
                    b.Navigation("Rapport");

                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Question", b =>
                {
                    b.Navigation("QuestionnaireQuestions");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Questionnaire", b =>
                {
                    b.Navigation("CampagneQuestionnaires");

                    b.Navigation("QuestionnaireQuestions");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Candidat", b =>
                {
                    b.Navigation("Candidatures");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("NeoEvaluation.API.Models.Personnel", b =>
                {
                    b.Navigation("CampagnesGerees");
                });
#pragma warning restore 612, 618
        }
    }
}
